### ISSUE TITLE
Forks to a page that doesn't exist

### ISSUE THREAD

**Issue by PreetiRS** [learn-co-curriculum/phase-1-arrow-functions#2]
The fork button leads to an error page.

**Comment by lizbur10** [comment]
Hi @PreetiRS! This time I got a 404 error the first time I clicked the fork button but it worked the second time I tried. This suggests that there may be some network instability going on, rather than a problem with the fork button itself. I'm going to close this issue as well, but please reopen it if you're continuing to have problems.

Thanks! 💙
